# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/fazabobi/Documents/Studies/tbfo/JBC-Tubes-IF2224-2026

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/fazabobi/Documents/Studies/tbfo/JBC-Tubes-IF2224-2026

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fazabobi/Documents/Studies/tbfo/JBC-Tubes-IF2224-2026/CMakeFiles /home/fazabobi/Documents/Studies/tbfo/JBC-Tubes-IF2224-2026//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fazabobi/Documents/Studies/tbfo/JBC-Tubes-IF2224-2026/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named arion_lexer_lib

# Build rule for target.
arion_lexer_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 arion_lexer_lib
.PHONY : arion_lexer_lib

# fast build rule for target.
arion_lexer_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arion_lexer_lib.dir/build.make CMakeFiles/arion_lexer_lib.dir/build
.PHONY : arion_lexer_lib/fast

#=============================================================================
# Target rules for targets named arion-lexer

# Build rule for target.
arion-lexer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 arion-lexer
.PHONY : arion-lexer

# fast build rule for target.
arion-lexer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arion-lexer.dir/build.make CMakeFiles/arion-lexer.dir/build
.PHONY : arion-lexer/fast

#=============================================================================
# Target rules for targets named arion_parser_lib

# Build rule for target.
arion_parser_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 arion_parser_lib
.PHONY : arion_parser_lib

# fast build rule for target.
arion_parser_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arion_parser_lib.dir/build.make CMakeFiles/arion_parser_lib.dir/build
.PHONY : arion_parser_lib/fast

#=============================================================================
# Target rules for targets named arion-parser

# Build rule for target.
arion-parser: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 arion-parser
.PHONY : arion-parser

# fast build rule for target.
arion-parser/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arion-parser.dir/build.make CMakeFiles/arion-parser.dir/build
.PHONY : arion-parser/fast

src/ms1-lexer/dfa/dfa.o: src/ms1-lexer/dfa/dfa.cpp.o
.PHONY : src/ms1-lexer/dfa/dfa.o

# target to build an object file
src/ms1-lexer/dfa/dfa.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arion_lexer_lib.dir/build.make CMakeFiles/arion_lexer_lib.dir/src/ms1-lexer/dfa/dfa.cpp.o
.PHONY : src/ms1-lexer/dfa/dfa.cpp.o

src/ms1-lexer/dfa/dfa.i: src/ms1-lexer/dfa/dfa.cpp.i
.PHONY : src/ms1-lexer/dfa/dfa.i

# target to preprocess a source file
src/ms1-lexer/dfa/dfa.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arion_lexer_lib.dir/build.make CMakeFiles/arion_lexer_lib.dir/src/ms1-lexer/dfa/dfa.cpp.i
.PHONY : src/ms1-lexer/dfa/dfa.cpp.i

src/ms1-lexer/dfa/dfa.s: src/ms1-lexer/dfa/dfa.cpp.s
.PHONY : src/ms1-lexer/dfa/dfa.s

# target to generate assembly for a file
src/ms1-lexer/dfa/dfa.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arion_lexer_lib.dir/build.make CMakeFiles/arion_lexer_lib.dir/src/ms1-lexer/dfa/dfa.cpp.s
.PHONY : src/ms1-lexer/dfa/dfa.cpp.s

src/ms1-lexer/lexer/lexer.o: src/ms1-lexer/lexer/lexer.cpp.o
.PHONY : src/ms1-lexer/lexer/lexer.o

# target to build an object file
src/ms1-lexer/lexer/lexer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arion_lexer_lib.dir/build.make CMakeFiles/arion_lexer_lib.dir/src/ms1-lexer/lexer/lexer.cpp.o
.PHONY : src/ms1-lexer/lexer/lexer.cpp.o

src/ms1-lexer/lexer/lexer.i: src/ms1-lexer/lexer/lexer.cpp.i
.PHONY : src/ms1-lexer/lexer/lexer.i

# target to preprocess a source file
src/ms1-lexer/lexer/lexer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arion_lexer_lib.dir/build.make CMakeFiles/arion_lexer_lib.dir/src/ms1-lexer/lexer/lexer.cpp.i
.PHONY : src/ms1-lexer/lexer/lexer.cpp.i

src/ms1-lexer/lexer/lexer.s: src/ms1-lexer/lexer/lexer.cpp.s
.PHONY : src/ms1-lexer/lexer/lexer.s

# target to generate assembly for a file
src/ms1-lexer/lexer/lexer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arion_lexer_lib.dir/build.make CMakeFiles/arion_lexer_lib.dir/src/ms1-lexer/lexer/lexer.cpp.s
.PHONY : src/ms1-lexer/lexer/lexer.cpp.s

src/ms1-lexer/lexer/symbolTable.o: src/ms1-lexer/lexer/symbolTable.cpp.o
.PHONY : src/ms1-lexer/lexer/symbolTable.o

# target to build an object file
src/ms1-lexer/lexer/symbolTable.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arion_lexer_lib.dir/build.make CMakeFiles/arion_lexer_lib.dir/src/ms1-lexer/lexer/symbolTable.cpp.o
.PHONY : src/ms1-lexer/lexer/symbolTable.cpp.o

src/ms1-lexer/lexer/symbolTable.i: src/ms1-lexer/lexer/symbolTable.cpp.i
.PHONY : src/ms1-lexer/lexer/symbolTable.i

# target to preprocess a source file
src/ms1-lexer/lexer/symbolTable.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arion_lexer_lib.dir/build.make CMakeFiles/arion_lexer_lib.dir/src/ms1-lexer/lexer/symbolTable.cpp.i
.PHONY : src/ms1-lexer/lexer/symbolTable.cpp.i

src/ms1-lexer/lexer/symbolTable.s: src/ms1-lexer/lexer/symbolTable.cpp.s
.PHONY : src/ms1-lexer/lexer/symbolTable.s

# target to generate assembly for a file
src/ms1-lexer/lexer/symbolTable.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arion_lexer_lib.dir/build.make CMakeFiles/arion_lexer_lib.dir/src/ms1-lexer/lexer/symbolTable.cpp.s
.PHONY : src/ms1-lexer/lexer/symbolTable.cpp.s

src/ms1-lexer/main.o: src/ms1-lexer/main.cpp.o
.PHONY : src/ms1-lexer/main.o

# target to build an object file
src/ms1-lexer/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arion-lexer.dir/build.make CMakeFiles/arion-lexer.dir/src/ms1-lexer/main.cpp.o
.PHONY : src/ms1-lexer/main.cpp.o

src/ms1-lexer/main.i: src/ms1-lexer/main.cpp.i
.PHONY : src/ms1-lexer/main.i

# target to preprocess a source file
src/ms1-lexer/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arion-lexer.dir/build.make CMakeFiles/arion-lexer.dir/src/ms1-lexer/main.cpp.i
.PHONY : src/ms1-lexer/main.cpp.i

src/ms1-lexer/main.s: src/ms1-lexer/main.cpp.s
.PHONY : src/ms1-lexer/main.s

# target to generate assembly for a file
src/ms1-lexer/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arion-lexer.dir/build.make CMakeFiles/arion-lexer.dir/src/ms1-lexer/main.cpp.s
.PHONY : src/ms1-lexer/main.cpp.s

src/ms1-lexer/token/token.o: src/ms1-lexer/token/token.cpp.o
.PHONY : src/ms1-lexer/token/token.o

# target to build an object file
src/ms1-lexer/token/token.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arion_lexer_lib.dir/build.make CMakeFiles/arion_lexer_lib.dir/src/ms1-lexer/token/token.cpp.o
.PHONY : src/ms1-lexer/token/token.cpp.o

src/ms1-lexer/token/token.i: src/ms1-lexer/token/token.cpp.i
.PHONY : src/ms1-lexer/token/token.i

# target to preprocess a source file
src/ms1-lexer/token/token.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arion_lexer_lib.dir/build.make CMakeFiles/arion_lexer_lib.dir/src/ms1-lexer/token/token.cpp.i
.PHONY : src/ms1-lexer/token/token.cpp.i

src/ms1-lexer/token/token.s: src/ms1-lexer/token/token.cpp.s
.PHONY : src/ms1-lexer/token/token.s

# target to generate assembly for a file
src/ms1-lexer/token/token.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arion_lexer_lib.dir/build.make CMakeFiles/arion_lexer_lib.dir/src/ms1-lexer/token/token.cpp.s
.PHONY : src/ms1-lexer/token/token.cpp.s

src/ms1-lexer/util/file.o: src/ms1-lexer/util/file.cpp.o
.PHONY : src/ms1-lexer/util/file.o

# target to build an object file
src/ms1-lexer/util/file.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arion_lexer_lib.dir/build.make CMakeFiles/arion_lexer_lib.dir/src/ms1-lexer/util/file.cpp.o
.PHONY : src/ms1-lexer/util/file.cpp.o

src/ms1-lexer/util/file.i: src/ms1-lexer/util/file.cpp.i
.PHONY : src/ms1-lexer/util/file.i

# target to preprocess a source file
src/ms1-lexer/util/file.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arion_lexer_lib.dir/build.make CMakeFiles/arion_lexer_lib.dir/src/ms1-lexer/util/file.cpp.i
.PHONY : src/ms1-lexer/util/file.cpp.i

src/ms1-lexer/util/file.s: src/ms1-lexer/util/file.cpp.s
.PHONY : src/ms1-lexer/util/file.s

# target to generate assembly for a file
src/ms1-lexer/util/file.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arion_lexer_lib.dir/build.make CMakeFiles/arion_lexer_lib.dir/src/ms1-lexer/util/file.cpp.s
.PHONY : src/ms1-lexer/util/file.cpp.s

src/ms2-parser/ParseNode.o: src/ms2-parser/ParseNode.cpp.o
.PHONY : src/ms2-parser/ParseNode.o

# target to build an object file
src/ms2-parser/ParseNode.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arion_parser_lib.dir/build.make CMakeFiles/arion_parser_lib.dir/src/ms2-parser/ParseNode.cpp.o
.PHONY : src/ms2-parser/ParseNode.cpp.o

src/ms2-parser/ParseNode.i: src/ms2-parser/ParseNode.cpp.i
.PHONY : src/ms2-parser/ParseNode.i

# target to preprocess a source file
src/ms2-parser/ParseNode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arion_parser_lib.dir/build.make CMakeFiles/arion_parser_lib.dir/src/ms2-parser/ParseNode.cpp.i
.PHONY : src/ms2-parser/ParseNode.cpp.i

src/ms2-parser/ParseNode.s: src/ms2-parser/ParseNode.cpp.s
.PHONY : src/ms2-parser/ParseNode.s

# target to generate assembly for a file
src/ms2-parser/ParseNode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arion_parser_lib.dir/build.make CMakeFiles/arion_parser_lib.dir/src/ms2-parser/ParseNode.cpp.s
.PHONY : src/ms2-parser/ParseNode.cpp.s

src/ms2-parser/Parser.o: src/ms2-parser/Parser.cpp.o
.PHONY : src/ms2-parser/Parser.o

# target to build an object file
src/ms2-parser/Parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arion_parser_lib.dir/build.make CMakeFiles/arion_parser_lib.dir/src/ms2-parser/Parser.cpp.o
.PHONY : src/ms2-parser/Parser.cpp.o

src/ms2-parser/Parser.i: src/ms2-parser/Parser.cpp.i
.PHONY : src/ms2-parser/Parser.i

# target to preprocess a source file
src/ms2-parser/Parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arion_parser_lib.dir/build.make CMakeFiles/arion_parser_lib.dir/src/ms2-parser/Parser.cpp.i
.PHONY : src/ms2-parser/Parser.cpp.i

src/ms2-parser/Parser.s: src/ms2-parser/Parser.cpp.s
.PHONY : src/ms2-parser/Parser.s

# target to generate assembly for a file
src/ms2-parser/Parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arion_parser_lib.dir/build.make CMakeFiles/arion_parser_lib.dir/src/ms2-parser/Parser.cpp.s
.PHONY : src/ms2-parser/Parser.cpp.s

src/ms2-parser/TreePrinter.o: src/ms2-parser/TreePrinter.cpp.o
.PHONY : src/ms2-parser/TreePrinter.o

# target to build an object file
src/ms2-parser/TreePrinter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arion_parser_lib.dir/build.make CMakeFiles/arion_parser_lib.dir/src/ms2-parser/TreePrinter.cpp.o
.PHONY : src/ms2-parser/TreePrinter.cpp.o

src/ms2-parser/TreePrinter.i: src/ms2-parser/TreePrinter.cpp.i
.PHONY : src/ms2-parser/TreePrinter.i

# target to preprocess a source file
src/ms2-parser/TreePrinter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arion_parser_lib.dir/build.make CMakeFiles/arion_parser_lib.dir/src/ms2-parser/TreePrinter.cpp.i
.PHONY : src/ms2-parser/TreePrinter.cpp.i

src/ms2-parser/TreePrinter.s: src/ms2-parser/TreePrinter.cpp.s
.PHONY : src/ms2-parser/TreePrinter.s

# target to generate assembly for a file
src/ms2-parser/TreePrinter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arion_parser_lib.dir/build.make CMakeFiles/arion_parser_lib.dir/src/ms2-parser/TreePrinter.cpp.s
.PHONY : src/ms2-parser/TreePrinter.cpp.s

src/ms2-parser/main.o: src/ms2-parser/main.cpp.o
.PHONY : src/ms2-parser/main.o

# target to build an object file
src/ms2-parser/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arion-parser.dir/build.make CMakeFiles/arion-parser.dir/src/ms2-parser/main.cpp.o
.PHONY : src/ms2-parser/main.cpp.o

src/ms2-parser/main.i: src/ms2-parser/main.cpp.i
.PHONY : src/ms2-parser/main.i

# target to preprocess a source file
src/ms2-parser/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arion-parser.dir/build.make CMakeFiles/arion-parser.dir/src/ms2-parser/main.cpp.i
.PHONY : src/ms2-parser/main.cpp.i

src/ms2-parser/main.s: src/ms2-parser/main.cpp.s
.PHONY : src/ms2-parser/main.s

# target to generate assembly for a file
src/ms2-parser/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arion-parser.dir/build.make CMakeFiles/arion-parser.dir/src/ms2-parser/main.cpp.s
.PHONY : src/ms2-parser/main.cpp.s

src/ms2-parser/parser_declarations.o: src/ms2-parser/parser_declarations.cpp.o
.PHONY : src/ms2-parser/parser_declarations.o

# target to build an object file
src/ms2-parser/parser_declarations.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arion_parser_lib.dir/build.make CMakeFiles/arion_parser_lib.dir/src/ms2-parser/parser_declarations.cpp.o
.PHONY : src/ms2-parser/parser_declarations.cpp.o

src/ms2-parser/parser_declarations.i: src/ms2-parser/parser_declarations.cpp.i
.PHONY : src/ms2-parser/parser_declarations.i

# target to preprocess a source file
src/ms2-parser/parser_declarations.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arion_parser_lib.dir/build.make CMakeFiles/arion_parser_lib.dir/src/ms2-parser/parser_declarations.cpp.i
.PHONY : src/ms2-parser/parser_declarations.cpp.i

src/ms2-parser/parser_declarations.s: src/ms2-parser/parser_declarations.cpp.s
.PHONY : src/ms2-parser/parser_declarations.s

# target to generate assembly for a file
src/ms2-parser/parser_declarations.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arion_parser_lib.dir/build.make CMakeFiles/arion_parser_lib.dir/src/ms2-parser/parser_declarations.cpp.s
.PHONY : src/ms2-parser/parser_declarations.cpp.s

src/ms2-parser/parser_expressions.o: src/ms2-parser/parser_expressions.cpp.o
.PHONY : src/ms2-parser/parser_expressions.o

# target to build an object file
src/ms2-parser/parser_expressions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arion_parser_lib.dir/build.make CMakeFiles/arion_parser_lib.dir/src/ms2-parser/parser_expressions.cpp.o
.PHONY : src/ms2-parser/parser_expressions.cpp.o

src/ms2-parser/parser_expressions.i: src/ms2-parser/parser_expressions.cpp.i
.PHONY : src/ms2-parser/parser_expressions.i

# target to preprocess a source file
src/ms2-parser/parser_expressions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arion_parser_lib.dir/build.make CMakeFiles/arion_parser_lib.dir/src/ms2-parser/parser_expressions.cpp.i
.PHONY : src/ms2-parser/parser_expressions.cpp.i

src/ms2-parser/parser_expressions.s: src/ms2-parser/parser_expressions.cpp.s
.PHONY : src/ms2-parser/parser_expressions.s

# target to generate assembly for a file
src/ms2-parser/parser_expressions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arion_parser_lib.dir/build.make CMakeFiles/arion_parser_lib.dir/src/ms2-parser/parser_expressions.cpp.s
.PHONY : src/ms2-parser/parser_expressions.cpp.s

src/ms2-parser/parser_statements.o: src/ms2-parser/parser_statements.cpp.o
.PHONY : src/ms2-parser/parser_statements.o

# target to build an object file
src/ms2-parser/parser_statements.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arion_parser_lib.dir/build.make CMakeFiles/arion_parser_lib.dir/src/ms2-parser/parser_statements.cpp.o
.PHONY : src/ms2-parser/parser_statements.cpp.o

src/ms2-parser/parser_statements.i: src/ms2-parser/parser_statements.cpp.i
.PHONY : src/ms2-parser/parser_statements.i

# target to preprocess a source file
src/ms2-parser/parser_statements.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arion_parser_lib.dir/build.make CMakeFiles/arion_parser_lib.dir/src/ms2-parser/parser_statements.cpp.i
.PHONY : src/ms2-parser/parser_statements.cpp.i

src/ms2-parser/parser_statements.s: src/ms2-parser/parser_statements.cpp.s
.PHONY : src/ms2-parser/parser_statements.s

# target to generate assembly for a file
src/ms2-parser/parser_statements.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arion_parser_lib.dir/build.make CMakeFiles/arion_parser_lib.dir/src/ms2-parser/parser_statements.cpp.s
.PHONY : src/ms2-parser/parser_statements.cpp.s

src/ms2-parser/parser_subprograms.o: src/ms2-parser/parser_subprograms.cpp.o
.PHONY : src/ms2-parser/parser_subprograms.o

# target to build an object file
src/ms2-parser/parser_subprograms.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arion_parser_lib.dir/build.make CMakeFiles/arion_parser_lib.dir/src/ms2-parser/parser_subprograms.cpp.o
.PHONY : src/ms2-parser/parser_subprograms.cpp.o

src/ms2-parser/parser_subprograms.i: src/ms2-parser/parser_subprograms.cpp.i
.PHONY : src/ms2-parser/parser_subprograms.i

# target to preprocess a source file
src/ms2-parser/parser_subprograms.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arion_parser_lib.dir/build.make CMakeFiles/arion_parser_lib.dir/src/ms2-parser/parser_subprograms.cpp.i
.PHONY : src/ms2-parser/parser_subprograms.cpp.i

src/ms2-parser/parser_subprograms.s: src/ms2-parser/parser_subprograms.cpp.s
.PHONY : src/ms2-parser/parser_subprograms.s

# target to generate assembly for a file
src/ms2-parser/parser_subprograms.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arion_parser_lib.dir/build.make CMakeFiles/arion_parser_lib.dir/src/ms2-parser/parser_subprograms.cpp.s
.PHONY : src/ms2-parser/parser_subprograms.cpp.s

src/ms2-parser/parser_toplevel.o: src/ms2-parser/parser_toplevel.cpp.o
.PHONY : src/ms2-parser/parser_toplevel.o

# target to build an object file
src/ms2-parser/parser_toplevel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arion_parser_lib.dir/build.make CMakeFiles/arion_parser_lib.dir/src/ms2-parser/parser_toplevel.cpp.o
.PHONY : src/ms2-parser/parser_toplevel.cpp.o

src/ms2-parser/parser_toplevel.i: src/ms2-parser/parser_toplevel.cpp.i
.PHONY : src/ms2-parser/parser_toplevel.i

# target to preprocess a source file
src/ms2-parser/parser_toplevel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arion_parser_lib.dir/build.make CMakeFiles/arion_parser_lib.dir/src/ms2-parser/parser_toplevel.cpp.i
.PHONY : src/ms2-parser/parser_toplevel.cpp.i

src/ms2-parser/parser_toplevel.s: src/ms2-parser/parser_toplevel.cpp.s
.PHONY : src/ms2-parser/parser_toplevel.s

# target to generate assembly for a file
src/ms2-parser/parser_toplevel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arion_parser_lib.dir/build.make CMakeFiles/arion_parser_lib.dir/src/ms2-parser/parser_toplevel.cpp.s
.PHONY : src/ms2-parser/parser_toplevel.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... arion-lexer"
	@echo "... arion-parser"
	@echo "... arion_lexer_lib"
	@echo "... arion_parser_lib"
	@echo "... src/ms1-lexer/dfa/dfa.o"
	@echo "... src/ms1-lexer/dfa/dfa.i"
	@echo "... src/ms1-lexer/dfa/dfa.s"
	@echo "... src/ms1-lexer/lexer/lexer.o"
	@echo "... src/ms1-lexer/lexer/lexer.i"
	@echo "... src/ms1-lexer/lexer/lexer.s"
	@echo "... src/ms1-lexer/lexer/symbolTable.o"
	@echo "... src/ms1-lexer/lexer/symbolTable.i"
	@echo "... src/ms1-lexer/lexer/symbolTable.s"
	@echo "... src/ms1-lexer/main.o"
	@echo "... src/ms1-lexer/main.i"
	@echo "... src/ms1-lexer/main.s"
	@echo "... src/ms1-lexer/token/token.o"
	@echo "... src/ms1-lexer/token/token.i"
	@echo "... src/ms1-lexer/token/token.s"
	@echo "... src/ms1-lexer/util/file.o"
	@echo "... src/ms1-lexer/util/file.i"
	@echo "... src/ms1-lexer/util/file.s"
	@echo "... src/ms2-parser/ParseNode.o"
	@echo "... src/ms2-parser/ParseNode.i"
	@echo "... src/ms2-parser/ParseNode.s"
	@echo "... src/ms2-parser/Parser.o"
	@echo "... src/ms2-parser/Parser.i"
	@echo "... src/ms2-parser/Parser.s"
	@echo "... src/ms2-parser/TreePrinter.o"
	@echo "... src/ms2-parser/TreePrinter.i"
	@echo "... src/ms2-parser/TreePrinter.s"
	@echo "... src/ms2-parser/main.o"
	@echo "... src/ms2-parser/main.i"
	@echo "... src/ms2-parser/main.s"
	@echo "... src/ms2-parser/parser_declarations.o"
	@echo "... src/ms2-parser/parser_declarations.i"
	@echo "... src/ms2-parser/parser_declarations.s"
	@echo "... src/ms2-parser/parser_expressions.o"
	@echo "... src/ms2-parser/parser_expressions.i"
	@echo "... src/ms2-parser/parser_expressions.s"
	@echo "... src/ms2-parser/parser_statements.o"
	@echo "... src/ms2-parser/parser_statements.i"
	@echo "... src/ms2-parser/parser_statements.s"
	@echo "... src/ms2-parser/parser_subprograms.o"
	@echo "... src/ms2-parser/parser_subprograms.i"
	@echo "... src/ms2-parser/parser_subprograms.s"
	@echo "... src/ms2-parser/parser_toplevel.o"
	@echo "... src/ms2-parser/parser_toplevel.i"
	@echo "... src/ms2-parser/parser_toplevel.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

